# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ueFile\UiFile\ProjectBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Episodes_shot = QtWidgets.QWidget()
        self.Episodes_shot.setEnabled(True)
        self.Episodes_shot.setObjectName("Episodes_shot")
        self.gridLayout = QtWidgets.QGridLayout(self.Episodes_shot)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.episodes = QtWidgets.QLabel(self.Episodes_shot)
        self.episodes.setObjectName("episodes")
        self.verticalLayout_2.addWidget(self.episodes)
        self.listepisodes = QtWidgets.QListWidget(self.Episodes_shot)
        self.listepisodes.setObjectName("listepisodes")
        self.verticalLayout_2.addWidget(self.listepisodes)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.shot = QtWidgets.QLabel(self.Episodes_shot)
        self.shot.setObjectName("shot")
        self.verticalLayout_3.addWidget(self.shot)
        self.listshot = QtWidgets.QListWidget(self.Episodes_shot)
        self.listshot.setObjectName("listshot")
        self.verticalLayout_3.addWidget(self.listshot)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.department = QtWidgets.QLabel(self.Episodes_shot)
        self.department.setObjectName("department")
        self.verticalLayout_4.addWidget(self.department)
        self.listdepartment = QtWidgets.QListWidget(self.Episodes_shot)
        self.listdepartment.setObjectName("listdepartment")
        self.verticalLayout_4.addWidget(self.listdepartment)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.depType = QtWidgets.QLabel(self.Episodes_shot)
        self.depType.setObjectName("depType")
        self.verticalLayout_5.addWidget(self.depType)
        self.listdepType = QtWidgets.QListWidget(self.Episodes_shot)
        self.listdepType.setObjectName("listdepType")
        self.verticalLayout_5.addWidget(self.listdepType)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.file = QtWidgets.QLabel(self.Episodes_shot)
        self.file.setObjectName("file")
        self.verticalLayout.addWidget(self.file)
        self.listfile = QtWidgets.QTableWidget(self.Episodes_shot)
        self.listfile.setMaximumSize(QtCore.QSize(120000, 1200))
        self.listfile.setObjectName("listfile")
        self.listfile.setColumnCount(4)
        self.listfile.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listfile.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listfile.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listfile.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listfile.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.listfile)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Episodes_shot, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 23))
        self.menubar.setObjectName("menubar")
        self.caoZhuo = QtWidgets.QMenu(self.menubar)
        self.caoZhuo.setObjectName("caoZhuo")
        MainWindow.setMenuBar(self.menubar)
        self.refresh = QtWidgets.QAction(MainWindow)
        self.refresh.setObjectName("refresh")
        self.caoZhuo.addAction(self.refresh)
        self.menubar.addAction(self.caoZhuo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.listepisodes)
        MainWindow.setTabOrder(self.listepisodes, self.listshot)
        MainWindow.setTabOrder(self.listshot, self.listdepartment)
        MainWindow.setTabOrder(self.listdepartment, self.listdepType)
        MainWindow.setTabOrder(self.listdepType, self.listfile)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.episodes.setText(_translate("MainWindow", "集数"))
        self.shot.setText(_translate("MainWindow", "镜头"))
        self.department.setText(_translate("MainWindow", "部门"))
        self.depType.setText(_translate("MainWindow", "类型"))
        self.file.setText(_translate("MainWindow", "文件"))
        item = self.listfile.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "版本"))
        item = self.listfile.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "概述"))
        item = self.listfile.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "制作人"))
        item = self.listfile.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "格式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Episodes_shot), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.caoZhuo.setTitle(_translate("MainWindow", "操作"))
        self.refresh.setText(_translate("MainWindow", "刷新"))
