# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\ueFile\UiFile\ProjectBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Episodes_shot = QtWidgets.QWidget()
        self.Episodes_shot.setEnabled(True)
        self.Episodes_shot.setObjectName("Episodes_shot")
        self.gridLayout = QtWidgets.QGridLayout(self.Episodes_shot)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.episodes = QtWidgets.QLabel(self.Episodes_shot)
        self.episodes.setObjectName("episodes")
        self.verticalLayout_2.addWidget(self.episodes)
        self.listWidget_2 = QtWidgets.QListWidget(self.Episodes_shot)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.shot = QtWidgets.QLabel(self.Episodes_shot)
        self.shot.setObjectName("shot")
        self.verticalLayout_3.addWidget(self.shot)
        self.listWidget_3 = QtWidgets.QListWidget(self.Episodes_shot)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_3.addWidget(self.listWidget_3)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.Episodes_shot)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.listWidget_4 = QtWidgets.QListWidget(self.Episodes_shot)
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_4.addWidget(self.listWidget_4)
        self.verticalLayout_4.setStretch(1, 2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.depType = QtWidgets.QLabel(self.Episodes_shot)
        self.depType.setObjectName("depType")
        self.verticalLayout_5.addWidget(self.depType)
        self.listWidget_5 = QtWidgets.QListWidget(self.Episodes_shot)
        self.listWidget_5.setObjectName("listWidget_5")
        self.verticalLayout_5.addWidget(self.listWidget_5)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.file = QtWidgets.QLabel(self.Episodes_shot)
        self.file.setObjectName("file")
        self.verticalLayout.addWidget(self.file)
        self.listWidget = QtWidgets.QListWidget(self.Episodes_shot)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Episodes_shot, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.listWidget_2)
        MainWindow.setTabOrder(self.listWidget_2, self.listWidget_3)
        MainWindow.setTabOrder(self.listWidget_3, self.listWidget_4)
        MainWindow.setTabOrder(self.listWidget_4, self.listWidget_5)
        MainWindow.setTabOrder(self.listWidget_5, self.listWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.episodes.setText(_translate("MainWindow", "episodes"))
        self.shot.setText(_translate("MainWindow", "shot"))
        self.label_4.setText(_translate("MainWindow", "department"))
        self.depType.setText(_translate("MainWindow", "depType"))
        self.file.setText(_translate("MainWindow", "file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Episodes_shot), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
