# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\teXiao\doodle\UiFile\setting.ui',
# licensing of 'C:\Users\teXiao\doodle\UiFile\setting.ui' applies.
#
# Created: Fri Aug 14 13:37:04 2020
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 547)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Department = QtWidgets.QLabel(self.centralwidget)
        self.Department.setMaximumSize(QtCore.QSize(30, 20))
        self.Department.setObjectName("Department")
        self.horizontalLayout.addWidget(self.Department)
        self.DepartmentTest = QtWidgets.QComboBox(self.centralwidget)
        self.DepartmentTest.setObjectName("DepartmentTest")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.horizontalLayout.addWidget(self.DepartmentTest)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user = QtWidgets.QLabel(self.centralwidget)
        self.user.setMaximumSize(QtCore.QSize(60, 30))
        self.user.setObjectName("user")
        self.horizontalLayout_2.addWidget(self.user)
        self.userTest = QtWidgets.QLineEdit(self.centralwidget)
        self.userTest.setObjectName("userTest")
        self.horizontalLayout_2.addWidget(self.userTest)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.syn = QtWidgets.QLabel(self.centralwidget)
        self.syn.setObjectName("syn")
        self.horizontalLayout_3.addWidget(self.syn)
        self.synTest = QtWidgets.QLineEdit(self.centralwidget)
        self.synTest.setObjectName("synTest")
        self.horizontalLayout_3.addWidget(self.synTest)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.sysTestYing = QtWidgets.QLabel(self.centralwidget)
        self.sysTestYing.setObjectName("sysTestYing")
        self.verticalLayout_2.addWidget(self.sysTestYing)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.synSever = QtWidgets.QLabel(self.centralwidget)
        self.synSever.setObjectName("synSever")
        self.horizontalLayout_6.addWidget(self.synSever)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.synEp = QtWidgets.QSpinBox(self.centralwidget)
        self.synEp.setMinimum(1)
        self.synEp.setMaximum(999)
        self.synEp.setObjectName("synEp")
        self.horizontalLayout_6.addWidget(self.synEp)
        self.horizontalLayout_6.setStretch(1, 2)
        self.horizontalLayout_6.setStretch(3, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.project = QtWidgets.QLabel(self.centralwidget)
        self.project.setObjectName("project")
        self.horizontalLayout_5.addWidget(self.project)
        self.projectCombo = QtWidgets.QComboBox(self.centralwidget)
        self.projectCombo.setObjectName("projectCombo")
        self.projectCombo.addItem("")
        self.projectCombo.addItem("")
        self.projectCombo.addItem("")
        self.projectCombo.addItem("")
        self.horizontalLayout_5.addWidget(self.projectCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.freeFileSync = QtWidgets.QLabel(self.centralwidget)
        self.freeFileSync.setObjectName("freeFileSync")
        self.verticalLayout_2.addWidget(self.freeFileSync)
        self.freeFileSyncButton = QtWidgets.QPushButton(self.centralwidget)
        self.freeFileSyncButton.setObjectName("freeFileSyncButton")
        self.verticalLayout_2.addWidget(self.freeFileSyncButton)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.pathSynSever = QtWidgets.QListWidget(self.centralwidget)
        self.pathSynSever.setObjectName("pathSynSever")
        self.horizontalLayout_4.addWidget(self.pathSynSever)
        self.pathSynLocale = QtWidgets.QListWidget(self.centralwidget)
        self.pathSynLocale.setObjectName("pathSynLocale")
        self.horizontalLayout_4.addWidget(self.pathSynLocale)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.menu.addAction(self.save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.Department.setText(QtWidgets.QApplication.translate("MainWindow", "部门", None, -1))
        self.DepartmentTest.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "未记录", None, -1))
        self.DepartmentTest.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Executive", None, -1))
        self.DepartmentTest.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Light", None, -1))
        self.DepartmentTest.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "VFX", None, -1))
        self.DepartmentTest.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "modle", None, -1))
        self.DepartmentTest.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "rig", None, -1))
        self.DepartmentTest.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Anm", None, -1))
        self.DepartmentTest.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "direct", None, -1))
        self.DepartmentTest.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "paint", None, -1))
        self.user.setText(QtWidgets.QApplication.translate("MainWindow", "用户名", None, -1))
        self.syn.setText(QtWidgets.QApplication.translate("MainWindow", "同步目录", None, -1))
        self.sysTestYing.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "服务器目录", None, -1))
        self.synSever.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "集数", None, -1))
        self.project.setText(QtWidgets.QApplication.translate("MainWindow", "project", None, -1))
        self.projectCombo.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "dubuxiaoyao", None, -1))
        self.projectCombo.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "changanhuanjie", None, -1))
        self.projectCombo.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "dubuxiaoyao3", None, -1))
        self.projectCombo.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "kuangshenmozun", None, -1))
        self.freeFileSync.setText(QtWidgets.QApplication.translate("MainWindow", "同步软件安装目录", None, -1))
        self.freeFileSyncButton.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.menu.setTitle(QtWidgets.QApplication.translate("MainWindow", "文件", None, -1))
        self.save.setText(QtWidgets.QApplication.translate("MainWindow", "保存", None, -1))

