# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 821, 194))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Department = QtWidgets.QLabel(self.layoutWidget)
        self.Department.setMaximumSize(QtCore.QSize(30, 20))
        self.Department.setObjectName("Department")
        self.horizontalLayout.addWidget(self.Department)
        self.DepartmentTest = QtWidgets.QComboBox(self.layoutWidget)
        self.DepartmentTest.setObjectName("DepartmentTest")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.DepartmentTest.addItem("")
        self.horizontalLayout.addWidget(self.DepartmentTest)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user = QtWidgets.QLabel(self.layoutWidget)
        self.user.setMaximumSize(QtCore.QSize(60, 30))
        self.user.setObjectName("user")
        self.horizontalLayout_2.addWidget(self.user)
        self.userTest = QtWidgets.QLineEdit(self.layoutWidget)
        self.userTest.setObjectName("userTest")
        self.horizontalLayout_2.addWidget(self.userTest)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.syn = QtWidgets.QLabel(self.layoutWidget)
        self.syn.setObjectName("syn")
        self.horizontalLayout_3.addWidget(self.syn)
        self.synTest = QtWidgets.QLineEdit(self.layoutWidget)
        self.synTest.setObjectName("synTest")
        self.horizontalLayout_3.addWidget(self.synTest)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.synSever = QtWidgets.QLabel(self.layoutWidget)
        self.synSever.setObjectName("synSever")
        self.verticalLayout_2.addWidget(self.synSever)
        self.sysTestYing = QtWidgets.QLabel(self.layoutWidget)
        self.sysTestYing.setObjectName("sysTestYing")
        self.verticalLayout_2.addWidget(self.sysTestYing)
        self.freeFileSync = QtWidgets.QLabel(self.layoutWidget)
        self.freeFileSync.setObjectName("freeFileSync")
        self.verticalLayout_2.addWidget(self.freeFileSync)
        self.freeFileSyncButton = QtWidgets.QPushButton(self.layoutWidget)
        self.freeFileSyncButton.setObjectName("freeFileSyncButton")
        self.verticalLayout_2.addWidget(self.freeFileSyncButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_4.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.menu.addAction(self.save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Department.setText(_translate("MainWindow", "部门"))
        self.DepartmentTest.setItemText(0, _translate("MainWindow", "未记录"))
        self.DepartmentTest.setItemText(1, _translate("MainWindow", "Light"))
        self.DepartmentTest.setItemText(2, _translate("MainWindow", "VFX"))
        self.DepartmentTest.setItemText(3, _translate("MainWindow", "modle"))
        self.DepartmentTest.setItemText(4, _translate("MainWindow", "rig"))
        self.DepartmentTest.setItemText(5, _translate("MainWindow", "Aim"))
        self.user.setText(_translate("MainWindow", "用户名"))
        self.syn.setText(_translate("MainWindow", "同步目录"))
        self.synSever.setText(_translate("MainWindow", "TextLabel"))
        self.sysTestYing.setText(_translate("MainWindow", "TextLabel"))
        self.freeFileSync.setText(_translate("MainWindow", "同步软件安装目录"))
        self.freeFileSyncButton.setText(_translate("MainWindow", "PushButton"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.save.setText(_translate("MainWindow", "保存"))
